# Generated by Django 4.0.4 on 2022-05-23 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_orderproduct_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderProduct',
        ),
    ]
